name: attendly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.2
  google_ml_kit: ^0.16.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  


flutter:
  uses-material-design: true

assets:
   - assets/mobilenet_v1_1.0_224.tflite